import { Programme, Milestone, EmailNotificationRecord } from '../types';
import { formatRM } from './dateUtils';

const DEFAULT_EMAIL = 'hafiz.wahab@mediaprima.com.my';
const EMAIL_KEY = 'paytrack_notification_email';
const ENABLED_KEY = 'paytrack_email_alerts_enabled';
const HISTORY_KEY = 'paytrack_email_history';

export function getNotificationEmail(): string {
  try {
    const saved = localStorage.getItem(EMAIL_KEY);
    return saved && saved.trim() ? saved.trim() : DEFAULT_EMAIL;
  } catch {
    return DEFAULT_EMAIL;
  }
}

export function setNotificationEmail(email: string): void {
  try {
    localStorage.setItem(EMAIL_KEY, email.trim());
  } catch (err) {
    console.error('Failed to save notification email', err);
  }
}

export function isAutoEmailAlertsEnabled(): boolean {
  try {
    const val = localStorage.getItem(ENABLED_KEY);
    return val === null ? true : val === 'true';
  } catch {
    return true;
  }
}

export function setAutoEmailAlertsEnabled(enabled: boolean): void {
  try {
    localStorage.setItem(ENABLED_KEY, String(enabled));
  } catch (err) {
    console.error('Failed to set auto email alerts', err);
  }
}

export function getEmailHistory(): EmailNotificationRecord[] {
  try {
    const data = localStorage.getItem(HISTORY_KEY);
    if (!data) return [];
    return JSON.parse(data);
  } catch {
    return [];
  }
}

export function saveEmailHistory(history: EmailNotificationRecord[]): void {
  try {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(history.slice(0, 50)));
  } catch (err) {
    console.error('Failed to save email history', err);
  }
}

export function sendPaymentDisbursementEmail(
  programme: Programme,
  milestone: Milestone,
  recipientOverride?: string
): EmailNotificationRecord {
  const recipient = recipientOverride || getNotificationEmail();
  const formattedAmount = formatRM(milestone.amount);
  const paidDate = milestone.paidDate || new Date().toISOString().split('T')[0];
  const contractRef = programme.contractRef || 'CON-MEDIA-PRIMA';

  const subject = `[PayTrack] Payment Disbursement Advice: ${programme.title} - ${milestone.title} (${formattedAmount})`;

  const body = `PAYMENT DISBURSEMENT ADVICE - MEDIA PRIMA TELEMETRY
======================================================
Status: SETTLED & CLEARED
Timestamp: ${new Date().toLocaleString('en-MY', { timeZone: 'Asia/Kuala_Lumpur' })}

PROGRAMME DETAILS:
------------------------------------------------------
Programme Title:       ${programme.title}
Contract Reference:    ${contractRef}
Agreement Sign Date:   ${programme.agreementSignDate || programme.createdAt}
Distributor / Vendor:  ${programme.vendor}
Rights Scope:          ${programme.rightsType || 'Linear & Digital Rights'}
Total Contract Value:  ${formatRM(programme.totalAmount)}

DISBURSEMENT BREAKDOWN:
------------------------------------------------------
Milestone Phase:       ${milestone.title}
Percentage:            ${milestone.percentage}%
Amount Disbursed:      ${formattedAmount}
Payment Date Settled:  ${paidDate}
Delivery Material:     Verified & Checked
Vendor Invoice:        Verified & Processed
System Reference:      TXN-${Date.now().toString(36).toUpperCase()}

RECIPIENT NOTIFICATION:
------------------------------------------------------
Dispatched to:         ${recipient}
System:                PayTrack Telemetry Engine v4.2.8
======================================================
This is an automated disbursement alert generated by PayTrack.`;

  const record: EmailNotificationRecord = {
    id: `email-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
    recipientEmail: recipient,
    programmeTitle: programme.title,
    contractRef,
    vendor: programme.vendor,
    milestoneTitle: milestone.title,
    amount: milestone.amount,
    paidDate,
    sentAt: new Date().toLocaleTimeString('en-MY', { hour: '2-digit', minute: '2-digit', second: '2-digit' }),
    subject,
    body,
    status: 'sent',
  };

  // Prepend to history
  const currentHistory = getEmailHistory();
  saveEmailHistory([record, ...currentHistory]);

  return record;
}

export function openMailtoDraft(record: EmailNotificationRecord): void {
  const mailtoUrl = `mailto:${encodeURIComponent(record.recipientEmail)}?subject=${encodeURIComponent(
    record.subject
  )}&body=${encodeURIComponent(record.body)}`;
  window.open(mailtoUrl, '_blank');
}
